# -*- coding: utf-8 -*-
"""Weighting1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fkd3w5keTNd6Noxxm3OmBCpuQ0zka-96
"""

# Subtask 1

pos = 0
neg = 0
for row in rows:
  if row['label']==1:
    pos+=1
  else:
    neg+=1

total=pos+neg

# ENS
weights = { 0: total*(1-0.9997)/(1-math.pow(0.9997,neg)), 1: total*(1-0.9997)/(1-math.pow(0.9997,pos))}
# INS
weights = { 0: total/neg, 1: total/pos}
# ISNS
weights = { 0: total/sqrt(neg), 1: total/sqrt(pos))}